spring.application.name=usuarios-api

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/usuarios}
spring.datasource.username=${DB_USER:usuarios}
spring.datasource.password=${DB_PASSWORD:usuarios}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.try-it-out-enabled=true
