name: Testes

on:
  push:
  pull_request:

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Permitir execução do Maven Wrapper
        run: chmod +x mvnw

      - name: Executar testes
        run: ./mvnw test
